/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#FFFFFF',
        'surface-dim': '#dbdad6',
        'surface-bright': '#faf9f5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f4f0',
        'surface-container': '#efeeea',
        'surface-container-high': '#e9e8e4',
        'surface-container-highest': '#e3e2df',
        'on-surface': '#1b1c1a',
        'on-surface-variant': '#3d4943',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ed',
        outline: '#6d7a73',
        'outline-variant': '#bccac1',
        'surface-tint': '#006c4e',
        primary: '#00694c',
        'on-primary': '#ffffff',
        'primary-container': '#008560',
        'on-primary-container': '#f5fff7',
        'inverse-primary': '#68dbae',
        secondary: '#5e5f5a',
        'on-secondary': '#ffffff',
        'secondary-container': '#e3e3dd',
        'on-secondary-container': '#646560',
        tertiary: '#145da3',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#3976be',
        'on-tertiary-container': '#fdfcff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#86f8c9',
        'primary-fixed-dim': '#68dbae',
        'on-primary-fixed': '#002115',
        'on-primary-fixed-variant': '#00513a',
        'secondary-fixed': '#e3e3dd',
        'secondary-fixed-dim': '#c7c7c1',
        'on-secondary-fixed': '#1b1c19',
        'on-secondary-fixed-variant': '#464743',
        'tertiary-fixed': '#d4e3ff',
        'tertiary-fixed-dim': '#a4c9ff',
        'on-tertiary-fixed': '#001c39',
        'on-tertiary-fixed-variant': '#004883',
        background: '#faf9f5',
        'on-background': '#1b1c1a',
        'surface-variant': '#e3e2df',
        'text-primary': '#1A1917',
        'text-secondary': '#6B6960',
        'text-muted': '#A8A69E',
        'accent-hover': '#0F6E56',
        'accent-soft': '#E1F5EE',
        warning: '#BA7517',
        'warning-soft': '#FAEEDA',
        danger: '#C0392B',
        'danger-soft': '#FDECEA',
        'border-subtle': 'rgba(0,0,0,0.09)',
        'border-strong': 'rgba(0,0,0,0.14)',
      },
      fontFamily: {
        sans: ['DM Sans', 'sans-serif'],
        mono: ['DM Mono', 'monospace'],
      },
      borderRadius: {
        'sm': '0.25rem', // 4px
        DEFAULT: '0.5rem', // 8px
        'md': '0.625rem', // 10px (radius-MD)
        'lg': '0.875rem', // 14px (radius-LG)
        'xl': '1.5rem',
        'full': '9999px', // Pill
      },
      spacing: {
        'base-unit': '4px',
        'gap-xs': '8px',
        'gap-md': '16px',
        'gap-lg': '24px',
        'sidebar-width': '220px',
        'topbar-height': '56px',
        'container-padding': '24px',
        'card-padding': '20px',
      },
    },
  },
  plugins: [],
}
